USE master
GO
DROP DATABASE QUANLY_NGOCMINH
GO
CREATE DATABASE QUANLY_NGOCMINH
GO
USE QUANLY_NGOCMINH
GO

CREATE TABLE HOKINHDOANH
(
	IDHOKD INT PRIMARY KEY,
	TENHOKINHDOANH	NVARCHAR(50),
	DIACHI	NVARCHAR(100),
	MASOTHUE  VARCHAR(50),
	SODIENTHOAI VARCHAR(20),
)
GO								 
									 
CREATE TABLE SANPHAM				 
(									 
	MASP	VARCHAR(30) PRIMARY KEY,						 
	TENSP	NVARCHAR(50),	
	DONVI   NVARCHAR(50),
)									 
									 
GO		
CREATE TABLE HOADONNHAP 			 
(									 
	MAHDNHAP	VARCHAR(30) PRIMARY KEY,	
	NGAYLAP	DATETIME,	 
	LYDO NVARCHAR(255),
	NGUOIBAN NVARCHAR(255),
	TENDONVI NVARCHAR(255),
	DIACHI NVARCHAR(255),
	MST VARCHAR(255),
	DIADIEMNHAPKHO NVARCHAR(255),
	THANHTIEN INTEGER,
)

GO

CREATE TABLE HOADONXUAT 			 
(									 
	MAHDXUAT	VARCHAR(30) PRIMARY KEY,	
	NGAYLAP	DATETIME,	 
	LYDO NVARCHAR(255),
	NGUOIMUA NVARCHAR(255),
	TENDONVI NVARCHAR(255),
	DIACHI NVARCHAR(255),
	MST VARCHAR(255),
	THANHTIEN INTEGER,

)
GO
CREATE TABLE CHITIETHOADONNHAP
(
	STT	INT IDENTITY  PRIMARY KEY ,
	MASP		VARCHAR(30),
	MAHDNHAP		VARCHAR(30),
	SOLUONG		INT,
	DONVI NVARCHAR(20),
	DONGIA INTEGER,
	FOREIGN KEY (MASP)  REFERENCES SANPHAM(MASP),
	FOREIGN KEY (MAHDNHAP)  REFERENCES HOADONNHAP(MAHDNHAP),

)
GO
CREATE TABLE CHITIETHOADONXUAT
(
	STT	INT IDENTITY  PRIMARY KEY ,
	MASP		VARCHAR(30),
	MAHDXUAT	VARCHAR(30),
	SOLUONG		INT,
	DONVI NVARCHAR(20),
	DONGIA INTEGER,
	FOREIGN KEY (MASP)  REFERENCES SANPHAM(MASP),
	FOREIGN KEY (MAHDXUAT)  REFERENCES HOADONXUAT(MAHDXUAT),

)
GO
set dateformat dmy 

